spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      #以下需要配置声名才能用
    initialSize: 5
    mainIdle: 5
    maxActive: 20
    maxWait: 60000
    imeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    #配置控制统计拦截的filter，去掉后监控见面sql无法统计，wall用于防火墙
    filters: stat,wall
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500